name: Deploy to Azure App Service
description: Deploy a Docker container to Azure App Service
inputs:
  app_name:
    required: true
    description: Azure App Service name
  resource_group:
    required: true
    description: Azure Resource Group name
  docker_image:
    required: true
    description: Full Docker image name with tag
  arm_client_id:
    required: true
    description: Azure ARM client ID for authentication
  arm_client_secret:
    required: true
    description: Azure ARM client secret for authentication
  arm_tenant_id:
    required: true
    description: Azure ARM tenant ID for authentication
  arm_subscription_id:
    required: true
    description: Azure ARM subscription ID for deployment

runs:
  using: "composite"
  steps:
    - name: Azure Login and Deploy Container
      shell: bash
      run: |
        # Azure Login
        az login --service-principal \
          --username ${{ inputs.arm_client_id }} \
          --password ${{ inputs.arm_client_secret }} \
          --tenant ${{ inputs.arm_tenant_id }} 
        
        az account set --subscription ${{ inputs.arm_subscription_id }}

        # Deploy Docker Container to Azure App Service
        az webapp config container set \
          --name ${{ inputs.app_name }} \
          --resource-group ${{ inputs.resource_group }} \
          --container-image-name ${{ inputs.docker_image }} \
          --docker-registry-server-url https://index.docker.io/v1