name: Deploy to Azure App Service
description: Deploy a Docker container to Azure App Service
inputs:
  app_name:
    required: true
    description: Azure App Service name
  resource_group:
    required: true
    description: Azure Resource Group name
  docker_image:
    required: true
    description: Full Docker image name with tag
  arm_client_id:
    required: true
    description: Azure ARM client ID for authentication
  arm_client_secret:
    required: true
    description: Azure ARM client secret for authentication
  arm_tenant_id:
    required: true
    description: Azure ARM tenant ID for authentication
  arm_subscription_id:
    required: true
    description: Azure ARM subscription ID for deployment

runs:
  using: "composite"
  steps:
    - name: Azure Login
      uses: Azure/login@v2.3.0
      with:
        creds: |
          {
            "clientId": "${{ inputs.arm_client_id }}",
            "clientSecret": "${{ inputs.arm_client_secret }}",
            "tenantId": "${{ inputs.arm_tenant_id }}",
            "subscriptionId": "${{ inputs.arm_subscription_id }}"
          }


    - name: Deploy Container
      uses: Azure/cli@v2.1.0
      with:
        inlineScript: |
          az webapp config container set \
            --name ${{ inputs.app_name }} \
            --resource-group ${{ inputs.resource_group }} \
            --container-image-name ${{ inputs.docker_image }} \
            --docker-registry-server-url https://index.docker.io/v1
