name: Deploy to Azure App Service
description: Deploy a Docker container to Azure App Service
inputs:
  app_name:
    required: true
    description: Azure App Service name
  resource_group:
    required: true
    description: Azure Resource Group name
  docker_image:
    required: true
    description: Full Docker image name with tag

  ARM_CLIENT_ID:
    required: true
  ARM_CLIENT_SECRET:
    required: true
  ARM_TENANT_ID:
    required: true
  ARM_SUBSCRIPTION_ID:
    required: true

runs:
  using: "composite"
  steps:
    - name: Azure Login
      shell: bash
      run: |
        az login --service-principal \
          --username ${{ inputs.ARM_CLIENT_ID }} \
          --password ${{ inputs.ARM_CLIENT_SECRET }} \
          --tenant ${{ inputs.ARM_TENANT_ID }} 
        
        az account set --subscription ${{ inputs.ARM_SUBSCRIPTION_ID }}

    - name: Deploy Container
      shell: bash
      uses: Azure/cli@v2.1.0
      with:
        inlineScript: |
          az webapp config container set \
          --name ${{ inputs.app_name }} \
          --resource-group ${{ inputs.resource_group }} \
          --container-image-name ${{ inputs.docker_image }}

    # - name: Azure CLI Action
    #   shell: bash
    #   uses: Azure/cli@v2.1.0
    #   with:
    #     inlineScript: |
    #       az webapp config container set --name dev-app-harirg-westus2 --resource-group dev-rg-harirg-westus2 --container-image-name gantahari/pygoatghaimage:15829659409
