name: CD-Pipeline

on:
  workflow_dispatch:
    inputs:
      ci_run_id:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download the Terraform Artifact
        uses: actions/download-artifact@v4.3.0
        with:
          name: terraformCode
          path: terraformCode
          run-id: ${{ github.event.inputs.ci_run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORMTOKEN }}
          
      # - name: terraform init
      #   run: |
      #     cd ${{ github.workspace }}/terraformCode
      #     export TF_WORKSPACE="dev"
      #     terraform init
      #     # terraform plan -var-file=variables/dev.tfvars
      #     terraform apply -auto-approve -var-file=variables/dev.tfvars


      - name: Deploy to AppService
        uses: ./.github/actions/deployToAppService
        with:
          app_name: dev-app-harirg-westus2
          resource_group: dev-rg-harirg-westus2
          # docker_image: ${{ vars.DOCKER_USER }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ github.event.inputs.ci_run_id }}
          docker_image: ${{ vars.DOCKER_USER }}/pygoatghaimage:15829659409 
          arm_token_client: ${{ secrets.ARM_TOKEN_CLIENT }}



      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://dev-app-harirg-westus2.azurewebsites.net/login/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'


  prod:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download the Terraform Artifact
        uses: actions/download-artifact@v4.3.0
        with:
          name: terraformCode
          path: terraformCode
          run-id: ${{ github.event.inputs.ci_run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORMTOKEN }}
          
      # - name: terraform init
      #   run: |
      #     cd ${{ github.workspace }}/terraformCode
      #     export TF_WORKSPACE="prod"
      #     terraform init
      #     # terraform plan -var-file=variables/prod.tfvars
      #     terraform apply -auto-approve -var-file=variables/prod.tfvars
      
     

      - name: Deploy to AppService
        uses: ./.github/actions/deployToAppService
        with:
          app_name: prod-app-harirg-westus2
          resource_group: prod-rg-harirg-westus2
          # docker_image: ${{ vars.DOCKER_USER }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ github.event.inputs.ci_run_id }}
          docker_image: ${{ vars.DOCKER_USER }}/pygoatghaimage:15829659409  
          arm_token_client: ${{ secrets.ARM_TOKEN_CLIENT }}



      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://dev-app-harirg-westus2.azurewebsites.net/login/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'